"""
数据库初始化工具
用于创建数据库表结构和导入初始数据
"""
import os
import sys
from config.config import config
from utils.database import DatabaseManager, get_database_manager
from utils.logger import sys_logger

logger = sys_logger.getChild('DB_Init')


def initialize_database():
    """初始化数据库"""
    print("=" * 60)
    print("数据库初始化工具")
    print("=" * 60)
    
    try:
        # 获取数据库管理器（会自动初始化表结构）
        db = get_database_manager(config)
        
        print("\n✓ 数据库初始化成功!")
        print(f"  - 数据库类型：{db.db_type}")
        print(f"  - 数据库路径：{db.db_path}")
        
        # 检查表是否创建成功
        tables = [
            'trade_logs',
            'orders',
            'positions',
            'accounts',
            'strategy_signals',
            'performance_metrics',
            'risk_events',
            'market_data'
        ]
        
        print("\n 已创建的表:")
        for table in tables:
            print(f"  ✓ {table}")
        
        return True
        
    except Exception as e:
        print(f"\n✗ 数据库初始化失败：{str(e)}")
        logger.error(f"初始化失败：{str(e)}", exc_info=True)
        return False


def insert_test_data():
    """插入测试数据"""
    print("\n" + "=" * 60)
    print("插入测试数据")
    print("=" * 60)
    
    try:
        db = get_database_manager(config)
        
        # 1. 插入测试订单
        from datetime import datetime
        test_order = {
            'order_id': 999999,
            'strategy_id': 'test_strategy',
            'symbol': '000001.SZ',
            'direction': 'BUY',
            'order_type': 'FIX',
            'price': 10.5,
            'volume': 1000,
            'filled_volume': 0,
            'filled_price': 0,
            'status': 'PENDING',
            'create_time': datetime.now(),
            'update_time': datetime.now(),
            'remark': 'Test order'
        }
        
        order_id = db.insert_order(test_order)
        print(f"✓ 插入测试订单，ID: {order_id}")
        
        # 2. 插入测试持仓
        test_position = {
            'symbol': '000001.SZ',
            'total_volume': 1000,
            'available_volume': 1000,
            'avg_price': 10.5,
            'current_price': 10.8,
            'market_value': 10800,
            'float_pnl': 300,
            'entry_date': datetime.now().date(),
            'update_time': datetime.now()
        }
        
        pos_id = db.upsert_position(test_position)
        print(f"✓ 插入测试持仓，ID: {pos_id}")
        
        # 3. 插入测试信号
        test_signal = {
            'strategy_name': 'test_strategy',
            'symbol': '000001.SZ',
            'signal_type': 'BUY',
            'signal_strength': 75.5,
            'price': 10.5,
            'volume': 1000,
            'reason': 'Test signal generated by AI',
            'create_time': datetime.now(),
            'executed': False
        }
        
        sig_id = db.insert_signal(test_signal)
        print(f"✓ 插入测试信号，ID: {sig_id}")
        
        # 4. 插入测试绩效
        test_perf = {
            'date': datetime.now().date(),
            'strategy_name': 'test_strategy',
            'total_return': 0.05,
            'daily_return': 0.01,
            'max_drawdown': -0.02,
            'sharpe_ratio': 1.5,
            'win_rate': 0.6,
            'profit_factor': 1.8,
            'trade_count': 10,
            'total_pnl': 2500
        }
        
        perf_id = db.insert_performance(test_perf)
        print(f"✓ 插入测试绩效，ID: {perf_id}")
        
        print("\n✓ 所有测试数据插入成功!")
        return True
        
    except Exception as e:
        print(f"\n✗ 插入测试数据失败：{str(e)}")
        logger.error(f"插入测试数据失败：{str(e)}", exc_info=True)
        return False


def query_sample_data():
    """查询示例数据"""
    print("\n" + "=" * 60)
    print("查询示例数据")
    print("=" * 60)
    
    try:
        db = get_database_manager(config)
        
        # 查询订单
        print("\n最近 5 条订单:")
        df_orders = db.get_orders()
        if not df_orders.empty:
            print(df_orders.tail())
        else:
            print("  (无订单数据)")
        
        # 查询持仓
        print("\n当前持仓:")
        df_positions = db.get_positions()
        if not df_positions.empty:
            print(df_positions)
        else:
            print("  (无持仓数据)")
        
        # 查询绩效
        print("\n最近绩效:")
        df_perf = db.get_performance_history()
        if not df_perf.empty:
            print(df_perf.head())
        else:
            print("  (无绩效数据)")
        
        return True
        
    except Exception as e:
        print(f"\n✗ 查询失败：{str(e)}")
        return False


def backup_database():
    """备份数据库"""
    print("\n" + "=" * 60)
    print("备份数据库")
    print("=" * 60)
    
    try:
        db = get_database_manager(config)
        
        backup_path = f"data/trading_backup_{__import__('datetime').datetime.now().strftime('%Y%m%d_%H%M%S')}.db"
        
        if db.backup_database(backup_path):
            print(f"✓ 数据库已备份到：{backup_path}")
            return True
        else:
            print("✗ 备份失败")
            return False
            
    except Exception as e:
        print(f"\n✗ 备份失败：{str(e)}")
        return False


def clear_old_data():
    """清理旧数据"""
    print("\n" + "=" * 60)
    print("清理旧数据")
    print("=" * 60)
    
    try:
        db = get_database_manager(config)
        
        days = 30  # 清理 30 天前的数据
        deleted = db.clear_old_data(days)
        
        print(f"✓ 已清理 {deleted} 条旧数据（>{days}天）")
        return True
        
    except Exception as e:
        print(f"\n✗ 清理失败：{str(e)}")
        return False


def export_to_csv():
    """导出数据到 CSV"""
    print("\n" + "=" * 60)
    print("导出数据到 CSV")
    print("=" * 60)
    
    try:
        db = get_database_manager(config)
        
        tables = ['orders', 'positions', 'performance_metrics']
        output_dir = 'data/exports'
        
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
        
        for table in tables:
            output_path = os.path.join(output_dir, f"{table}.csv")
            if db.export_to_csv(table, output_path):
                print(f"✓ 已导出 {table} 到 {output_path}")
        
        return True
        
    except Exception as e:
        print(f"\n✗ 导出失败：{str(e)}")
        return False


def main():
    """主函数"""
    import argparse
    
    parser = argparse.ArgumentParser(description='数据库初始化和维护工具')
    parser.add_argument('--init', action='store_true', help='初始化数据库')
    parser.add_argument('--test-data', action='store_true', help='插入测试数据')
    parser.add_argument('--query', action='store_true', help='查询示例数据')
    parser.add_argument('--backup', action='store_true', help='备份数据库')
    parser.add_argument('--clear', action='store_true', help='清理旧数据')
    parser.add_argument('--export', action='store_true', help='导出数据到 CSV')
    parser.add_argument('--all', action='store_true', help='执行所有操作')
    
    args = parser.parse_args()
    
    if args.all:
        # 执行所有操作
        initialize_database()
        insert_test_data()
        query_sample_data()
        backup_database()
        clear_old_data()
        export_to_csv()
    else:
        # 执行指定操作
        if args.init:
            initialize_database()
        if args.test_data:
            insert_test_data()
        if args.query:
            query_sample_data()
        if args.backup:
            backup_database()
        if args.clear:
            clear_old_data()
        if args.export:
            export_to_csv()
    
    print("\n" + "=" * 60)
    print("操作完成!")
    print("=" * 60)


if __name__ == "__main__":
    main()
